sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.3

install:
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

env:
  global:
    secure: "AJKYhQL4DdUFIKqx0axRgH8TR05irBMb62PeJxLW1cvr1HynIfha8w7HDnTEeUDQ/Xwb1LrVKxnPNR8X8yNjQKGnDeFf3qOfhxgur82jke6JD8nrDj5gFICkohXXCsRXdKgEEhVGLkZF1EZWtZCFpogpRNJYwEXkithUZvhBWSHPMFw0Q3DMN/ud5/il0lxLg9cfwLjwaADad28u0/x2oILGEkFK1s76+xu15LFya9hLd6b+mGpCGRf3NW4w2CCQOcqNH7iHax6AVciCMUS9WEZcL2umqq2zYYtLYp6Kn57hs+Bj9vsc7ZXn9PjZ3TlETxjExEyMfpVSOzFpKC1vyVBwR4MPtcaFoYj+YBNV9wlBMik/mxFFcgAFs9S492Y+E2RjOQNUSAZWQ6MLJO8S/PtbEeW79xvFF3vSmuDDpCWQ9d8QR8zMDuFtJJu40lwqVcDEjX/3m0vkZNMnWRIwshPdYTqp/YiUg8hHgbxXTz71Nzer+xhqzT+rRboin/r5gzWYdNDj52+zBhTW2nIzeANbch74TYVAdhZIUZjjXtuFgtMOVrfPwL81rkCYKYkeLzHPHtnWoeSeHq7sM7D7G+TmqOmT31dNVWhXeOVy3bMayXt5O1hswCD/r0w4SGNUKrCuSu6rdqB6yoD92a5YFa/429057X15efUR4hZIt8U="
branches:
  only:
    - master
