backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/media
public_folder: /media

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}--{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}